import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/custom/Navbar'
import Footer from '@/components/custom/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='bg-neutral-100 text-neutral-900 dark:bg-neutral-900 dark:text-neutral-100'>
        <div className='flex flex-col min-h-screen'>
          <header>
            <Navbar />
          </header>

          <main className='flex-1'>{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  )
}
